"""empty message

Revision ID: 68fa6cc7e28d
Revises: None
Create Date: 2021-06-20 21:57:24.905408

"""

# revision identifiers, used by Alembic.
revision = '68fa6cc7e28d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
